"""delete_unused

Revision ID: 1a4e978d89b2
Revises: 2376d1059227
Create Date: 2026-03-09 20:51:29.888848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a4e978d89b2'
down_revision: Union[str, Sequence[str], None] = '2376d1059227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'is_active', schema='short-link')
    op.drop_column('links', 'user_registred', schema='short-link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('user_registred', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='short-link')
    op.add_column('links', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='short-link')
    # ### end Alembic commands ###
