"""add_expires_at

Revision ID: 2376d1059227
Revises: 9d5fb5579abf
Create Date: 2026-03-09 19:01:40.826067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2376d1059227'
down_revision: Union[str, Sequence[str], None] = '9d5fb5579abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('links', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True), schema='short-link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'expires_at', schema='short-link')
    # ### end Alembic commands ###
