"""initial

Revision ID: 9d5fb5579abf
Revises: 
Create Date: 2026-03-09 13:56:05.536708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d5fb5579abf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS "short-link"')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='short-link'
    )
    op.create_index(op.f('ix_short-link_users_email'), 'users', ['email'], unique=True, schema='short-link')
    op.create_index(op.f('ix_short-link_users_id'), 'users', ['id'], unique=False, schema='short-link')
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('transitions', sa.Integer(), nullable=False),
    sa.Column('last_transition_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_registred', sa.Boolean(), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['short-link.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='short-link'
    )
    op.create_index(op.f('ix_short-link_links_id'), 'links', ['id'], unique=False, schema='short-link')
    op.create_index(op.f('ix_short-link_links_original_url'), 'links', ['original_url'], unique=False, schema='short-link')
    op.create_index(op.f('ix_short-link_links_project'), 'links', ['project'], unique=False, schema='short-link')
    op.create_index(op.f('ix_short-link_links_short_code'), 'links', ['short_code'], unique=True, schema='short-link')
    op.create_index(op.f('ix_short-link_links_user_id'), 'links', ['user_id'], unique=False, schema='short-link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('short_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('transitions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_transition_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_registred', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('project', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('links_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('links_pkey'))
    )
    op.create_index(op.f('ix_links_user_id'), 'links', ['user_id'], unique=False)
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    op.create_index(op.f('ix_links_project'), 'links', ['project'], unique=False)
    op.create_index(op.f('ix_links_original_url'), 'links', ['original_url'], unique=False)
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_short-link_links_user_id'), table_name='links', schema='short-link')
    op.drop_index(op.f('ix_short-link_links_short_code'), table_name='links', schema='short-link')
    op.drop_index(op.f('ix_short-link_links_project'), table_name='links', schema='short-link')
    op.drop_index(op.f('ix_short-link_links_original_url'), table_name='links', schema='short-link')
    op.drop_index(op.f('ix_short-link_links_id'), table_name='links', schema='short-link')
    op.drop_table('links', schema='short-link')
    op.drop_index(op.f('ix_short-link_users_id'), table_name='users', schema='short-link')
    op.drop_index(op.f('ix_short-link_users_email'), table_name='users', schema='short-link')
    op.drop_table('users', schema='short-link')
    op.execute('DROP SCHEMA IF EXISTS "short-link"')
    # ### end Alembic commands ###
